// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrajoaawocymldlphxre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyYWpvYWF3b2N5bWxkbHBoeHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MTkyNjgsImV4cCI6MjA1NDQ5NTI2OH0.nHUApNr72lxpsYAitdW9iXu6i0LiuSlCeepV1qcrq4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);