<<<<<<< HEAD
=======

>>>>>>> c9af91c62fcaf3a7daa80ec56c6537ac01608061
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Retrieve environment variables with fallbacks to prevent errors
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// Check if required configuration is available
if (!SUPABASE_URL) {
<<<<<<< HEAD
  console.error('❌ CRITICAL: Missing VITE_SUPABASE_URL environment variable.');
  console.info('Please make sure you have a .env file in your project root with VITE_SUPABASE_URL defined.');
}

if (!SUPABASE_ANON_KEY) {
  console.error('❌ CRITICAL: Missing VITE_SUPABASE_ANON_KEY environment variable.');
  console.info('Please make sure you have a .env file in your project root with VITE_SUPABASE_ANON_KEY defined.');
}

// Create the Supabase client
let supabaseClient = null;

try {
  if (SUPABASE_URL && SUPABASE_ANON_KEY) {
    supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
    console.info('✅ Supabase client initialized successfully');
  }
} catch (error) {
  console.error('❌ Failed to initialize Supabase client:', error);
}

// Export the configured client
export const supabase = supabaseClient || {
  from: (table) => {
    console.error(`❌ Supabase client is not initialized. Cannot query table "${table}"`);
    return {
      select: () => ({ data: null, error: new Error('Supabase client not initialized') }),
      insert: () => ({ data: null, error: new Error('Supabase client not initialized') }),
      update: () => ({ data: null, error: new Error('Supabase client not initialized') }),
      delete: () => ({ data: null, error: new Error('Supabase client not initialized') }),
      order: () => ({ data: null, error: new Error('Supabase client not initialized') })
    };
  }
};
=======
  console.warn('Missing VITE_SUPABASE_URL environment variable. Supabase client will be null.');
}

if (!SUPABASE_ANON_KEY) {
  console.warn('Missing VITE_SUPABASE_ANON_KEY environment variable. Supabase client will be null.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = SUPABASE_URL && SUPABASE_ANON_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY)
  : null as any; // Fallback to avoid runtime crashes, but will show clear console warning
>>>>>>> c9af91c62fcaf3a7daa80ec56c6537ac01608061
